name: petowner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

    # firebase suite
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore:
  firebase_app_check: ^0.0.6+3
  firebase_messaging: ^11.2.4
  firebase_storage: ^10.2.4
  firebase_remote_config: ^1.0.3

  # stacked
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  logger: ^1.1.0

  # in-house libraries
  pawcastle_phoneauth:
    git:
      url: https://github.com/MovingMelody/pawcastle-phoneauth.git
      ref: main

  pawcastle_designsystem:
    git:
      url: https://github.com/MovingMelody/pawcastle-designsystem-flutter.git
      ref: main

  pawcastle_datamodels:
    git:
      url: https://github.com/MovingMelody/pawcastle-datamodels.git
      ref: main

  # helper to deal with multiple languages
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  # location
  geocoding: ^2.0.0
  geolocator: ^7.2.0+1
  geoflutterfire: ^3.0.1


  # handle necessary permissions
  permission_handler: ^8.1.4+2

  dotted_border: ^2.0.0
  url_launcher: ^6.0.9

  hive: ^2.0.4
  path_provider: ^2.0.7

  flutter_dotenv: ^5.0.0
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.9.1
  carousel_slider: ^4.0.0
  flutter_rating_stars: ^1.0.3+4
  fluttertoast: ^8.0.8
  share: ^2.0.4
  avatar_glow: ^2.0.1
  package_info: ^2.0.2
  razorpay_flutter: ^1.2.7
  badges: ^2.0.1
  auto_size_text: ^3.0.0
  agora_rtc_engine: ^5.2.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  stacked_generator: ^0.5.6
  mockito:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icons/app_icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - .env

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/ms-regular.ttf
          weight: 400
        - asset: assets/fonts/ms-smbold.ttf
          weight: 600
        - asset: assets/fonts/ms-bold.ttf
          weight: 700
    - family: IconPack
      fonts:
        - asset: assets/fonts/IconPack.ttf

